[versions]
#Libraries
core-ktx = "1.12.0"
room = "2.6.1"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-recyclerview = "1.3.2"
androidx-swiperefreshlayout = "1.1.0"
androidx-activity = "1.8.2"
androidx-lifecycle-viewmodel-ktx = "2.7.0"
androidx-navigation = "2.7.7"
android-material = "1.11.0"
android-play-services-location = "21.2.0"
okhttp3-logging-interceptor = "4.11.0"
retrofit2 = "2.9.0"
hilt-android = "2.46.1"
glide = "4.15.1"
firebase-boom = "32.8.0"
junit = "4.13.2"
androidx-test-ext = "1.1.5"
androidx-test-runner = "1.5.2"
androidx-test-rules = "1.5.0"
androidx-test-espresso-core = "3.5.1"
coroutines = "1.7.1"
mockito-kotlin = "5.2.0"
mockito-inline = "5.2.0"
cash-turbine = "0.13.0"

#Plugins
android-gradle-plugin = "8.2.0"
kotlin-android-plugin = "1.9.10"
google-services-plugin = "4.4.1"
firebase-crashlytics-plugin = "2.9.9"
navigation-safeargs-plugin = "2.7.7"
dagger-hilt-android-plugin = "2.46.1"

[libraries]
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }
android-play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "android-play-services-location" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidx-swiperefreshlayout"}

androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

firebase-boom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-boom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3-logging-interceptor" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-android" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt-android"}

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner"}
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules"}
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-core" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin"}
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito-inline"}
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines"}
cash-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "cash-turbine"}

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-safeargs-plugin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt-android-plugin" }

[bundles]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx"]
retrofit2 = ["retrofit2", "retrofit2-converter-gson", "okhttp3-logging-interceptor"]
androidx-navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx"]
firebase = ["firebase-analytics", "firebase-crashlytics"]
mockito = ["mockito-kotlin", "mockito-inline"]
